[tool.poetry]
name = "finstmt-lint"
description = "Linting for finstmt"
version = "1.0.0"
authors = ["Nick DeRobertis <whoopnip@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
finstmt = {path = "../..", develop = true}
flake8 = "*"
mypy = "*"