#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Workaround to get lint-staged to work outside of main shell
# (e.g. Git GUIs)
ASDF_PATH=$(realpath ~/.asdf/shims)
PATH="$ASDF_PATH:$PATH" npx --no -- commitlint --edit "$1"
